### ISSUE TITLE
Commodity Generation Enhancement

### ISSUE THREAD

**Issue by pixelhater** [RyanYoung25/UndiscoveredWorlds#10]
When determining what items the merchant will sell, select x number of items from a particular commodity type (can be duplicates) at random based on the availability rating for that commodity.

For example:
A terrestrial world has an organic rating of 10, so ten items with the organic type would be selected from the list. In this example the following 10 are selected:
Foodstuffs
Foodstuffs
Textiles
Foodstuffs
Rations
Pharmaceuticals
Rations
Liquor
Seeds
Seeds

**Comment by RyanYoung25** [comment]
If it works that's great. Glad you fixed it. 

----- Reply message -----

**Comment by jonathanmcdaniel** [comment]
I think this is a suggestion. I dont think its in the game yet.

**Comment by jonathanmcdaniel** [comment]
Can we make it so that the player starts with items that are logical for a ship to have? Some food, rations, extra fuel tanks, etc.? I think this would give a somewhat more realistic feel to the game and will also allow the player to sell items from the beginning. We could also give them these items and take away all of their money so depending on where they sell their items, they begin with a variable amount of money.

**Comment by pixelhater** [comment]
Just implemented this feature. The port should generate at least one of each item class in addition to it's expected inventory. I tested it and it seemed to work perfectly. Let me know if you encounter any weirdness and I'll fix it.
